# Generated by Django 6.0.3 on 2026-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmessage_is_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='hero/'),
        ),
    ]
